version: '3.8'

services:
  app:
    build: .
    container_name: library-app
    ports:
      - "3000:3000"  # Expose the app on port 3000
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs # Persist logs on host machine
    env_file:
      - .env  # Load environment variables from .env file
    command: node server.js  # Start the application

  db:
    image: postgres:latest
    container_name: library-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}  # Load from .env file
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"  # Host machine 5433 -> Container 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Run initial SQL script

volumes:
  postgres_data:
