version: '3.8'

services:
  app:
    build: .
    container_name: library-app
    ports:
      - "3000:3000"  # Change this to match your Express app's PORT
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs # Persist logs on host machine
    environment:
      - NODE_ENV=production
      - DB_URL=${DB_URL}  # Use Render’s External Database URL
      - PORT=3000  # Ensure your Express app uses this port
      - API_KEY=API123
    command: node server.js  # Start the app

  db:
    image: postgres:latest
    container_name: library-db
    restart: always
    environment:
      POSTGRES_USER: library_mgmt_user
      POSTGRES_PASSWORD: your_db_password  # Ensure this matches Render DB password
      POSTGRES_DB: library_mgmt
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
